=== RubenAgudo/MIPS/TFG/LoadDataModel.xsd
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="ObservationModel" type="ObservationModelType"/>
	
	<!--Tipo complejo que identifica al ObservationModel-->
	<xs:complexType name="ObservationModelType">

		<xs:sequence>

			<xs:element name="EspObservation" type="EspObservationType" minOccurs="1" maxOccurs="unbounded" />
			
		</xs:sequence>
		
		<xs:attribute name="name" type="xs:string"/>
		
	</xs:complexType>
	
	<!--Tipo complejo que identifica los EspObservations-->
	<xs:complexType name="EspObservationType" >

		<xs:sequence>

			<xs:element name="InputData" type="InputDataType" minOccurs="0" maxOccurs="1" />
			<xs:element name="Properties" type="PropertiesType" minOccurs="1" maxOccurs="1" />
			
		</xs:sequence>

		<xs:attribute name="name" use="required" />
		<xs:attribute name="description" use="optional" />
		
	</xs:complexType>

	<!--Tipo complejo para los datos constantes InputData-->
	<xs:complexType name="InputDataType" >

		<xs:sequence>

			<xs:element name="IData" type="IDataType" minOccurs="0" maxOccurs="unbounded"/>
			
		</xs:sequence>
		
	</xs:complexType>

	<!--Tipo complejo que identifica cada campo constante IData-->
	<xs:complexType name="IDataType" >

		<xs:attribute name="id" type="xs:string"/>
		
	</xs:complexType>
	
	<!--Tipo complejo que identifica el campo propiedades, que contiene una lista de EspProperty-->
	<xs:complexType name="PropertiesType" >

		<xs:sequence>

			<xs:element name="EspProperty" type="EspPropertyType" minOccurs="1" maxOccurs="unbounded" />
			
		</xs:sequence>
		
	</xs:complexType>

	<!-- Definicion del campo EspProperty, que lo unico que contiene son los atributos-->
	<xs:complexType name="EspPropertyType" >

		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="type" type="xs:string" />
		
	</xs:complexType>
	
</xs:schema>

=== RubenAgudo/MIPS/TFG/ObservationModelExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<ObservationModel name="KinectOM.xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="src\\schemas\\LoadDataModel.xsd">

	<EspObservation name="observacion1">

		<Properties>
			<EspProperty name="prop11" type="1" />
			<EspProperty name="prop12" type="1" />
			<EspProperty name="prop13" type="1" />
			<EspProperty name="prop14" type="1" />
			<EspProperty name="prop15" type="0" />
		</Properties>
		
	</EspObservation>

	<EspObservation name="observacion2">

		<Properties>
			<EspProperty name="prop21" type="1" />
			<EspProperty name="prop22" type="0" />
		</Properties>

	</EspObservation>
	
</ObservationModel>

=== RubenAgudo/MIPS/TFG/XMLFile1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ObservationModel name="KinectOM.xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="LoadDataModel.xsd">

	<EspObservation name="Axis">
		<InputData>
			<IData id="Skeleton" />
			<IData id="TrackingState" />
			<IData id="FinKinect" />
			<IData id="Train" />
			<IData id="Save" />
			<IData id="SituacionSaque"/>
		</InputData>

		<Properties>
			<EspProperty name="Matrix" type="string" />
			<EspProperty name="Matrix2" type="string" />
			<EspProperty name="Matrix3" type="string" />
			<EspProperty name="Matrix4" type="string" />
			<EspProperty name="Matrix5" type="string" />
			<EspProperty name="Matrix6" type="string" />
			<EspProperty name="Matrix7" type="string" />
		</Properties>
		
	</EspObservation>

	<EspObservation name="Axis2">
		<InputData>
			<IData id="Skeleton" />
			<IData id="TrackingState" />
			<IData id="FinKinect" />
			<IData id="Train" />
			<IData id="Save" />
			<IData id="SituacionSaque"/>
		</InputData>

		<Properties>
			<EspProperty name="Matrix" type="string" />
			<EspProperty name="Matrix2" type="string" />
			<EspProperty name="Matrix3" type="string" />
			<EspProperty name="Matrix4" type="string" />
			<EspProperty name="Matrix5" type="string" />
			<EspProperty name="Matrix6" type="string" />
			<EspProperty name="Matrix7" type="string" />
		</Properties>

	</EspObservation>
	
</ObservationModel>
